### ISSUE TITLE
Invalid json in .babelrc

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit-envs#41]
This project https://github.com/muicss/mui/blob/master/.babelrc have an invalid json in the babelrc file.
so bit status is getting an error.

github repo: https://github.com/muicss/mui/
commit hash: 924c60151ecff1e9feaffe9d3858a6b5085c9274
bit command that i run: bit status 
[bitjson&bitmap.zip](https://github.com/teambit/bit-envs/files/2460166/bitjson.bitmap.zip)

**Comment by qballer** [comment]
this issue may be resolved by using JSON5.parse when we read babel. Should be a rather easy fix.

cc: @imsnif

**Comment by JoshK2** [comment]
I do a pull request to this file, and the change was merged to the master.
