### ISSUE TITLE
Resolve modules not working in cube-ui with vue dependencies

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit-envs#62]
github: https://github.com/didi/cube-ui
commit hash: 320f372954fd521f7e2db25bfad2f2989990f6b3
[bitmap&bitjson.zip](https://github.com/teambit/bit-envs/files/2486879/bitmap.bitjson.zip)

the project have vue dependencies and few files do require like this:
import Vue from 'vue2'
and vue2 not exist, so i write resolve modules and its not working.

just for testing i replace 'vue2' in 'vue' in few files and run bit status and its working.

**Comment by GiladShoham** [comment]
This is issue with Bit not with envs. closing this. will handle it under Bit's issues
