### ISSUE TITLE
Module ts-jest was not found (grommet)

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit-envs#77]
when i run test i get this error:
Module ts-jest in the transform option was not found.
so i installed it, and get another error.
I also try to set user config to default and its not working.

bitmap and bitjson:
[bitjson&bitmap.zip](https://github.com/teambit/bit-envs/files/2545935/bitjson.bitmap.zip)
link to tar:
https://drive.google.com/file/d/1EE9xZUjWhYzOIIJomorOHlXT7U737Pz0/view?usp=sharing

**Comment by guysaar223** [comment]
also on reactstrap:

[reactstrap.tar.gz](https://drive.google.com/file/d/1bnZg4Lzb0q7ZG4ZXuagv_JGkWaTeUgXi/view?usp=sharing)
